apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: Spark
  name: spark-slaves
spec:
  replicas: 3
  selector:
    app: Spark
    deploymentconfig: spark-slaves
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: Spark
        deploymentconfig: spark-slaves
    spec:
      containers:
      - env:
        - name: SPARK_TYPE
          value: slave
        - name: MASTER_SPARK_URL
          value: spark-master:7077
        image: tomihararznde/spark-cluster:latest
        imagePullPolicy: Always
        name: spark-slaves
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 1m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
