apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: Spark
  name: spark-master
spec:
  replicas: 1
  selector:
    app: Spark
    deploymentconfig: spark-master
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: Spark
        deploymentconfig: spark-master
    spec:
      containers:
      - env:
        - name: SPARK_TYPE
          value: master
        image: tomihararznde/spark-cluster:latest
        imagePullPolicy: Always
        name: spark-master
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 1m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
