apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: Spark
  name: spark-master
spec:
  ports:
  - name: web-ui
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: svc-port
    port: 7077
    protocol: TCP
    targetPort: 7077
  selector:
    app: Spark
    deploymentconfig: spark-master
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
